lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    #    token_ttl: 3600 # en segundos, el valor predeterminado es 3600
    user_id_claim: email  # Se usa el email como identificador del usuario
    encoder:
        service: lexik_jwt_authentication.encoder.lcobucci
    token_extractors:
        authorization_header:
            enabled: true
            prefix:  Bearer
            name:    Authorization
        query_parameter:
            enabled: true
            name:    token
        cookie:
            enabled: false